
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;

public class Employee {

    private final String firstName;
    private final String lastName;
    private int mailboxCapacity;
    private String departmentName;
    private String password;
    private final String companyName;
    private String email;

    public Employee(String firstName, String lastName, String companyName, String dept, int mailboxCapacity) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.companyName = companyName;
        this.mailboxCapacity = mailboxCapacity;
        this.departmentName = dept;

        if (dept.equalsIgnoreCase("sales") || dept.equalsIgnoreCase("accounting") || dept.equalsIgnoreCase("development")) {
            this.departmentName = dept.toLowerCase();
        } else {
            this.departmentName = "";
        }
    }

    public String generatePassword() {
        String alphaNumeric = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "0123456789" + "abcdefghijklmnopqrstuvxyz";
        StringBuilder sb = new StringBuilder();
        int index = (int) (alphaNumeric.length() * Math.random());
        for (int i = 0; i < 10; i++) {
            sb.append(alphaNumeric.charAt(index));
        }

        if (password != null && password.equalsIgnoreCase(sb.toString())) {
            generatePassword();
        }
        System.out.println("New Pwd:" + sb + " old pwd: " + this.password);
        this.password = sb.toString();
        System.out.println("PASSWORD GENERATED: " + sb);
        return sb.toString();
    }

    public String generateEmail() {
        email = firstName + "." + lastName + "@" + departmentName + "." + companyName + ".com";
        System.out.println("EMAIL GENERATED: " + email);
        return email;
    }

    public String changePassword() {
        Scanner scan = new Scanner(System.in);
        System.out.println("Do you want to set a user-defined password or a computer generated one?");
        String userInput = scan.nextLine();

        if (userInput.toLowerCase().contains("computer")) {
            String newPassword = generatePassword();
            System.out.println("Password has been randomly generated by computer: " + newPassword);
            return newPassword;
        } else if (userInput.toLowerCase().contains("user")) {
            System.out.println("Please enter your new password");
            String userPassword = scan.nextLine();
            if (!userPassword.equalsIgnoreCase(password)) {
                System.out.println("New Pwd:" + userPassword + " old pwd: " + password);
                this.password = userPassword;
                System.out.println("Password has been changed by user to: " + userPassword);
                return userPassword;
            } else {
                System.out.println("Your new password matches your old password. Please try again");
                changePassword();
            }
        } else {
            System.out.println("Wrong input. Please check choices again and choose user or computer.");
        }
        return "";
    }

    public int getMailboxCapacity() {
        return mailboxCapacity;
    }

    public void setMailboxCapacity(int m) {
        if (mailboxCapacity != m) {
            this.mailboxCapacity = m;
            System.out.println("MAILBOX CAPACITY SET TO: " + mailboxCapacity);
        } else {
            System.out.println("Error: Capacity of mailbox is already " + mailboxCapacity +
                    " and you are trying to set it to " + m);
        }
    }

    public String setAlternateEmail(String email) {
        this.email = email;
        System.out.println("EMAIL GENERATED: " + this.email);
        return email;
    }

    public String getEmail() {
        return email;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public String getName() {
        return firstName + " " + lastName;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", mailboxCapacity=" + mailboxCapacity +
                ", departmentName='" + departmentName + '\'' +
                ", password='" + password + '\'' +
                ", companyName='" + companyName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }

    public void writeFile()
    {
        try
        {
            FileWriter in = new FileWriter("src/info.txt");
            in.write("First Name: "+this.firstName);
            in.append("\nLast Name: "+this.lastName);
            in.append("\nEmail: "+this.email);
            in.append("\nPassword: "+this.password);
            in.append("\nCapacity: "+this.mailboxCapacity);
            in.append("\nAlternate Email ID: "+this.email);
            in.close();

            System.out.println("Data Stored");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void readFile(String fileName)
    {
        try
        {
            FileReader fileReader = new FileReader(fileName);
            int i;

            while((i=fileReader.read())!=-1)
            {
                System.out.println((char)(i));
            }
            fileReader.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
}
